### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by appachey** [appachey/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ExpertSkte** [comment]
#### LANGUAGES
🇺🇸 ENGLISH 🇨🇳 MANDARIN 🇯🇵 JAPANESE

#### SKILLS  

KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS

#### CHARACTER  

NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE

#### LIFE LESSON
You must defeat Sheng Long to stand a chance.

#### LIKES 😃  

GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY

#### DISLIKES 😞  

BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES

#### WANTS 🥺
BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY

#### PUBLICATIONS

<small>2011</small>
The true and humble story of me under pseudonim Tyler Wilde in an article "The evolution of Ken and Ryu"

<small>2003-2018</small>
For 15 years I have published comic books with Udon Entertainment depicting my adventures, bitter lessons and great victories.

------

#### LIFE & EDUCATION
To live is to fight and to fight is to live.
I  started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.

**Comment by appachey** [comment]
Nice work!

**Comment by ExpertSkte** [comment]
<section>
  <h3>Languages</h3>
  <p class="tags small"><span class="language" lang="mn">&#x1f1f2;&#x1f1f3; MANDARIN</span> <span class="language" lang="jp">&#x1F1EF;&#x1f1f5; JAPANESE</span> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
</section>

**Comment by ExpertSkte** [comment]
<section>
  <h3>Skills</h3>
  <p class="tags small">KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS</p>
</section>

**Comment by ExpertSkte** [comment]
<section>
  <h3>Character</h3>
  <p class="tags small">NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE</p>
</section>
<section>
  <h3>Life lesson</h3>
  <p class="tags small">You must defeat Sheng Long to stand a chance.</p>
</section>
<section>
  <h3>Likes&#x1f603;</h3>
  <p class="tags small">GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY</p>
</section>
<section>
  <h3>Dislikes&#x1f61e;</h3>
  <p class="tags small">BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES</p>
</section>
<section>
  <h3>Wants&#x1f97a;</h3>
  <p class="tags small bulleted">BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</p>
</section>

**Comment by ExpertSkte** [comment]
<section>
  <h3>Life & Education</h3>
  <ul class="timeline">
    <li>
      <div><em>Credo</em></div>
      <p class="tags bulleted">To live is to fight and to fight is to live.</p>
    </li>
    <li>
      <div><em>Unknown</em></div>
      <div><strong>I  started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.</strong></div>
    </li>
  </ul>
</section>

**Comment by ExpertSkte** [comment]
<section>
  <h3>Publications</h3>
  <div><em>2011</em></div>
  <p>The true and humble story of me under pseudonim Tyler Wilde in an article "The evolution of Ken and Ryu"</p>
  <div><em>2003 &ndash; 2018</em></div>
  <p>For 15 years I have published comic books with Udon Entertainment depicting my adventures, bitter lessons and great victories.</p>
</section>
